/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controler.BotigaCtl;
import model.Videojoc;

/**
 *
 * @author usuari
 */
public class Pantalla extends javax.swing.JFrame {

    private BotigaCtl bctl;

    /**
     * Creates new form Pantalla
     */
    public Pantalla(BotigaCtl bctl) {
        this.bctl = bctl;
        initComponents();
    }
/**
 * Valida el codi si esta buit i si el codi esta repetit i el camp es obligatori
 * @return boolean
 */
    private boolean validaCodi() {
        boolean valida = false;
        String text = this.codiText.getText();
        if (bctl.validarBuit(text)) {
            errorCodiLabel.setText("Camp obligatori");
        } else {
            try {

                int codi = Integer.parseInt(text);
                if (bctl.buscarVideojoc(codi) != null) {
                    errorCodiLabel.setText("Codi repetit");

                } else {
                    errorCodiLabel.setText("");
                    valida = true;
                }
            } catch (Exception e) {
                System.out.println(e.toString());
            }
        }
        return valida;
    }
/**
 * Valida el nom si esta buit i et diu si es un camp obligatori
 * @return boolean
 */
    private boolean validaNom() {
        boolean valida = false;
        String text = this.nomText.getText();
        if (bctl.validarBuit(text)) {
            errorNomLabel.setText("Camp obligatori");
        } else {
            errorNomLabel.setText("");
            valida = true;
        }
        return valida;
    }
/**
 * Valida la plataforma si esta buida i si el camp es obligatori
 * @return boolean
 */
    private boolean validaPlataforma() {
        boolean valida = false;
        String text = this.plataformaText.getText();
        if (bctl.validarBuit(text)) {
            errorPlataformaLabel.setText("Camp obligatori");
        } else {
            errorPlataformaLabel.setText("");
            valida = true;
        }
        return valida;
    }
/**
 * Valida la quantitat d'estoc si esta buida i si es un camp obligatori
 * @return boolean
 */
    private boolean validaQStock() {
        boolean valida = false;
        String text = this.qStockText.getText();
        if (bctl.validarBuit(text)) {
            errorQStockLabel.setText("Camp obligatori");
        } else {
            errorQStockLabel.setText("");
            valida = true;
        }
        return valida;
    }
/**
 * Vakuda el preu si esta buida i si es un camp obligatori
 * @return boolean
 */
    private boolean validaPreu() {
        boolean valida = false;
        String text = this.preuText.getText();
        if (bctl.validarBuit(text)) {
            errorPreuLabel.setText("Camp obligatori");
        } else {
            errorPreuLabel.setText("");
            valida = true;
        }
        return valida;
    }
/**
 * Si el valor no esta seleccionat dona null sino retorna un string amb el valor de la tematica
 * @return null o String
 */
    private String donamTematica() {
        String text = null;
        if (oci.isSelected()) {
            text = "oci";
        } else if (artistic.isSelected()) {
            text = "Artistic";
        } else if (educatiu.isSelected()) {
            text = "Educatiu";
        }
        return text;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        categoria = new javax.swing.JComboBox<>();
        afegir = new javax.swing.JButton();
        codiLabel = new javax.swing.JLabel();
        oci = new javax.swing.JRadioButton();
        artistic = new javax.swing.JRadioButton();
        educatiu = new javax.swing.JRadioButton();
        codiText = new javax.swing.JTextField();
        nomLabel = new javax.swing.JLabel();
        nomText = new javax.swing.JTextField();
        categoriaLabel = new javax.swing.JLabel();
        plataformaLabel = new javax.swing.JLabel();
        plataformaText = new javax.swing.JTextField();
        qStockLabel = new javax.swing.JLabel();
        qStockText = new javax.swing.JTextField();
        preuLabel = new javax.swing.JLabel();
        preuText = new javax.swing.JTextField();
        ofertaLabel = new javax.swing.JLabel();
        siOfertaCheck = new javax.swing.JCheckBox();
        tematicaLabel = new javax.swing.JLabel();
        errorCodiLabel = new javax.swing.JLabel();
        errorNomLabel = new javax.swing.JLabel();
        errorPlataformaLabel = new javax.swing.JLabel();
        errorQStockLabel = new javax.swing.JLabel();
        errorPreuLabel = new javax.swing.JLabel();
        Llista = new javax.swing.JButton();
        errorTematicaLabel = new javax.swing.JLabel();
        errorCategoriaLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        categoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "------", "Accio", "Estrategia", "Simulacio", "Rol" }));
        categoria.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                categoriaFocusLost(evt);
            }
        });

        afegir.setText("Afegir Videojoc");
        afegir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                afegirActionPerformed(evt);
            }
        });

        codiLabel.setText("Codi");

        buttonGroup1.add(oci);
        oci.setText("Oci");
        oci.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                ociFocusLost(evt);
            }
        });

        buttonGroup1.add(artistic);
        artistic.setText("Artistic");
        artistic.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                artisticFocusLost(evt);
            }
        });

        buttonGroup1.add(educatiu);
        educatiu.setText("Educatiu");
        educatiu.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                educatiuFocusLost(evt);
            }
        });

        codiText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                codiTextFocusLost(evt);
            }
        });
        codiText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                codiTextKeyTyped(evt);
            }
        });

        nomLabel.setText("Nom");

        nomText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                nomTextFocusLost(evt);
            }
        });
        nomText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomTextActionPerformed(evt);
            }
        });

        categoriaLabel.setText("Categoria");

        plataformaLabel.setText("Plataforma");

        plataformaText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                plataformaTextFocusLost(evt);
            }
        });
        plataformaText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                plataformaTextKeyTyped(evt);
            }
        });

        qStockLabel.setText("Quantitati de Stock");

        qStockText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                qStockTextFocusLost(evt);
            }
        });
        qStockText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                qStockTextKeyTyped(evt);
            }
        });

        preuLabel.setText("Preu");

        preuText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                preuTextFocusLost(evt);
            }
        });
        preuText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                preuTextKeyTyped(evt);
            }
        });

        ofertaLabel.setText("Oferta");

        siOfertaCheck.setText("En Oferta");

        tematicaLabel.setText("Tematica");

        Llista.setText("Llista");
        Llista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LlistaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(qStockLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ofertaLabel)
                            .addComponent(siOfertaCheck)
                            .addComponent(preuLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tematicaLabel)
                                    .addComponent(oci))
                                .addGap(61, 61, 61)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(categoriaLabel)
                                    .addComponent(categoria, 0, 215, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(preuText)
                                    .addComponent(qStockText)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(artistic)
                                    .addComponent(educatiu)
                                    .addComponent(errorTematicaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(errorQStockLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(errorPreuLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(errorCategoriaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Llista)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(afegir))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(nomLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                                        .addComponent(codiLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(plataformaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(codiText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 331, Short.MAX_VALUE)
                                    .addComponent(nomText)
                                    .addComponent(plataformaText, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(errorCodiLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(errorNomLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(errorPlataformaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE))))))
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codiLabel)
                    .addComponent(codiText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(errorCodiLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomLabel)
                    .addComponent(nomText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(errorNomLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(plataformaText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(errorPlataformaLabel)
                    .addComponent(plataformaLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(qStockLabel)
                    .addComponent(qStockText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(errorQStockLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(preuLabel)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(preuText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(errorPreuLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ofertaLabel)
                    .addComponent(tematicaLabel)
                    .addComponent(categoriaLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(siOfertaCheck)
                    .addComponent(oci)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(categoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(errorCategoriaLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(artistic)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(educatiu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(afegir)
                    .addComponent(Llista)
                    .addComponent(errorTematicaLabel))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void codiTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_codiTextKeyTyped
        // TODO add your handling code here:

        char c = evt.getKeyChar();

        if (c < '0' || c > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_codiTextKeyTyped

    private void nomTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomTextActionPerformed
        // TODO add your handling code here:
        // text nom

    }//GEN-LAST:event_nomTextActionPerformed

    private void afegirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_afegirActionPerformed
        // TODO add your handling code here:
        boolean bC = validaCodi();
        boolean bN = validaNom();
        boolean bPl = validaPlataforma();
        boolean bQS = validaQStock();
        boolean bPr = validaPreu();
        String tm = donamTematica();

        if (tm == null) {
            errorTematicaLabel.setText("Camp Obligatori");
        } else {
            errorTematicaLabel.setText("");
        }

        if (categoria.getSelectedIndex() == 0) {
            errorCategoriaLabel.setText("Camp Obligatori");
        } else {
            errorCategoriaLabel.setText("");
        }

        if (bC && bN && bPl && bQS && bPr && tm != null && categoria.getSelectedIndex() != 0) {

            Videojoc vj = new Videojoc();
            int codi = Integer.parseInt(this.codiText.getText());
            int qStock = Integer.parseInt(this.qStockText.getText());
            double preu = Double.parseDouble(this.preuText.getText());
            String cat = String.valueOf(categoria.getSelectedItem());
            String plat = this.plataformaText.getText();

            vj.setCodi(codi);
            vj.setNom(this.nomText.getText());
            vj.setPlataforma(plat);
            vj.setQuantStock(qStock);
            vj.setPreu(preu);
            if (siOfertaCheck.isSelected()) {
                vj.setOferta("Oferta");
            } else {
                vj.setOferta("Sense Oferta");
            }
            vj.setCategoria(cat);
            vj.setTematica(tm);

            bctl.afegirVideojoc(vj);
            //   bctl.setEscritura(oos, mgz);

            codiText.setText("");
            nomText.setText("");
            plataformaText.setText("");
            qStockText.setText("");
            preuText.setText("");
            buttonGroup1.clearSelection();
            categoria.setSelectedIndex(0);
            siOfertaCheck.setSelected(false);
        }

    }//GEN-LAST:event_afegirActionPerformed

    private void qStockTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qStockTextKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();

        if (c < '0' || c > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_qStockTextKeyTyped

    private void preuTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_preuTextKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();

        if (!((c >= '0' && c <= '9') || (c == '.' || c == ','))) {
            evt.consume();
        }
    }//GEN-LAST:event_preuTextKeyTyped

    private void plataformaTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_plataformaTextKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (plataformaText.getText().trim().length() > 2) {
            evt.consume();
        }

    }//GEN-LAST:event_plataformaTextKeyTyped

    private void codiTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_codiTextFocusLost
        // TODO add your handling code here:

        validaCodi();
    }//GEN-LAST:event_codiTextFocusLost

    private void nomTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nomTextFocusLost
        // TODO add your handling code here:
        validaNom();
    }//GEN-LAST:event_nomTextFocusLost

    private void plataformaTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_plataformaTextFocusLost
        // TODO add your handling code here:
        validaPlataforma();
    }//GEN-LAST:event_plataformaTextFocusLost

    private void qStockTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_qStockTextFocusLost
        // TODO add your handling code here:
        validaQStock();
    }//GEN-LAST:event_qStockTextFocusLost

    private void preuTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_preuTextFocusLost
        // TODO add your handling code here:
        validaPreu();
    }//GEN-LAST:event_preuTextFocusLost

    private void LlistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LlistaActionPerformed
        // TODO add your handling code here:
        //llista
        bctl.mostraLlista();

    }//GEN-LAST:event_LlistaActionPerformed

    private void categoriaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_categoriaFocusLost
        // TODO add your handling code here:
          if (categoria.getSelectedIndex() == 0) {
            errorCategoriaLabel.setText("Camp Obligatori");
        } else {
            errorCategoriaLabel.setText("");
        }
    }//GEN-LAST:event_categoriaFocusLost

    private void ociFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ociFocusLost
        // TODO add your handling code here:
        if (donamTematica() == null) {
            errorTematicaLabel.setText("Camp Obligatori");
        } else {
            errorTematicaLabel.setText("");
        }
    }//GEN-LAST:event_ociFocusLost

    private void artisticFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_artisticFocusLost
        // TODO add your handling code here:
        if (donamTematica() == null) {
            errorTematicaLabel.setText("Camp Obligatori");
        } else {
            errorTematicaLabel.setText("");
        }
    }//GEN-LAST:event_artisticFocusLost

    private void educatiuFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_educatiuFocusLost
        // TODO add your handling code here:
        if (donamTematica() == null) {
            errorTematicaLabel.setText("Camp Obligatori");
        } else {
            errorTematicaLabel.setText("");
        }
    }//GEN-LAST:event_educatiuFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pantalla(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Llista;
    private javax.swing.JButton afegir;
    private javax.swing.JRadioButton artistic;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> categoria;
    private javax.swing.JLabel categoriaLabel;
    private javax.swing.JLabel codiLabel;
    private javax.swing.JTextField codiText;
    private javax.swing.JRadioButton educatiu;
    private javax.swing.JLabel errorCategoriaLabel;
    private javax.swing.JLabel errorCodiLabel;
    private javax.swing.JLabel errorNomLabel;
    private javax.swing.JLabel errorPlataformaLabel;
    private javax.swing.JLabel errorPreuLabel;
    private javax.swing.JLabel errorQStockLabel;
    private javax.swing.JLabel errorTematicaLabel;
    private javax.swing.JLabel nomLabel;
    private javax.swing.JTextField nomText;
    private javax.swing.JRadioButton oci;
    private javax.swing.JLabel ofertaLabel;
    private javax.swing.JLabel plataformaLabel;
    private javax.swing.JTextField plataformaText;
    private javax.swing.JLabel preuLabel;
    private javax.swing.JTextField preuText;
    private javax.swing.JLabel qStockLabel;
    private javax.swing.JTextField qStockText;
    private javax.swing.JCheckBox siOfertaCheck;
    private javax.swing.JLabel tematicaLabel;
    // End of variables declaration//GEN-END:variables

}
