/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controler.*;
import java.sql.SQLException;
import javax.swing.table.TableModel;
import model.*;

/**
 *
 * @author usuari
 */
public class VistaPrincipal extends javax.swing.JFrame {

    private LlistaCtl llctl;
    String codi;

    /**
     * Creates new form VistaPrincipal
     */
    public VistaPrincipal(LlistaCtl llctl) {
        this.llctl = llctl;
        initComponents();
        modificarBut.setEnabled(false);
        esborrarBut.setEnabled(false);
    }
    
   

    public void setCategoriaCombo() {
        categoriaCB.setModel(llctl.getCategorias());
    }

    public void setTable() throws SQLException {
        TableModel tm = llctl.getVaixellsDataTable("...", 0);
        taula.setModel(tm);
    }

    public void setEnableModYEsb() {
        modificarBut.setEnabled(true);
        esborrarBut.setEnabled(true);
    }

    public void switchCategoriaYOrdre() {
        try {

            String cate = String.valueOf(categoriaCB.getSelectedItem());

//            int iCat = categoriaCB.getSelectedIndex();
//            String cate = categoriaCB.getItemAt(iCat);
            int ordre = ordenarCB.getSelectedIndex();
            TableModel tm = llctl.getVaixellsDataTable(cate, ordre);
            taula.setModel(tm);
        } catch (Exception e) {
            System.out.println(e.toString());
            e.printStackTrace();
        }
    }
    
    private void getCodiSeleccionat(){
        int fila = taula.getSelectedRow();
        String codi = taula.getValueAt(fila, 0).toString();
        this.codi = codi;
    }
    
    public String getCodi(){
        return this.codi;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        categoriaCB = new javax.swing.JComboBox<>();
        ordenarCB = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        taula = new javax.swing.JTable();
        esborrarBut = new javax.swing.JButton();
        modificarBut = new javax.swing.JButton();
        afegirBut = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        categoriaCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        categoriaCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoriaCBActionPerformed(evt);
            }
        });

        ordenarCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Codi", "Temps Compensat" }));
        ordenarCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ordenarCBActionPerformed(evt);
            }
        });

        taula.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        taula.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                taulaFocusGained(evt);
            }
        });
        taula.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                taulaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(taula);

        esborrarBut.setText("Esborrar");
        esborrarBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                esborrarButActionPerformed(evt);
            }
        });

        modificarBut.setText("Modificar");
        modificarBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarButActionPerformed(evt);
            }
        });

        afegirBut.setText("Afegir");
        afegirBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                afegirButActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(categoriaCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ordenarCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(afegirBut)
                        .addGap(18, 18, 18)
                        .addComponent(modificarBut)
                        .addGap(18, 18, 18)
                        .addComponent(esborrarBut))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 611, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ordenarCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(categoriaCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(afegirBut)
                    .addComponent(esborrarBut)
                    .addComponent(modificarBut))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void afegirButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_afegirButActionPerformed
        // TODO add your handling code here:
        llctl.mostraVistaAf();
    }//GEN-LAST:event_afegirButActionPerformed

    private void modificarButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarButActionPerformed
        // TODO add your handling code here:
        llctl.mostraVistaMod();
    }//GEN-LAST:event_modificarButActionPerformed

    private void taulaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_taulaFocusGained
        // TODO add your handling code here:
//        modificarBut.setEnabled(true);
//        esborrarBut.setEnabled(true);

//        int fila = taula.getSelectedRow();
//        int columna = taula.getSelectedColumn();
//        Object codi = taula.getValueAt(fila, columna);
//        System.out.println(codi.toString());

    }//GEN-LAST:event_taulaFocusGained

    private void taulaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_taulaMouseClicked
        // TODO add your handling code here:
        setEnableModYEsb();       
        getCodiSeleccionat();
        // VistaAfegirYModificar.codiText.setText(codi); 
    }//GEN-LAST:event_taulaMouseClicked

    private void categoriaCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoriaCBActionPerformed
        // TODO add your handling code here:
        switchCategoriaYOrdre();
    }//GEN-LAST:event_categoriaCBActionPerformed

    private void ordenarCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ordenarCBActionPerformed
        // TODO add your handling code here:
        switchCategoriaYOrdre();
    }//GEN-LAST:event_ordenarCBActionPerformed

    private void esborrarButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_esborrarButActionPerformed
        // TODO add your handling code here:
        int codi = Integer.parseInt(this.codi);
        try{
        llctl.eliminarVaixell(codi);
        }catch(Exception e){
            System.out.println(e.toString());
            e.printStackTrace();
        }
    }//GEN-LAST:event_esborrarButActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaPrincipal(null).setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton afegirBut;
    private javax.swing.JComboBox<String> categoriaCB;
    private javax.swing.JButton esborrarBut;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton modificarBut;
    private javax.swing.JComboBox<String> ordenarCB;
    private javax.swing.JTable taula;
    // End of variables declaration//GEN-END:variables
}
